# File: .github/workflows/android.yml
# Created: 2025-06-04
# Author: Vishalsnw
# Last Modified: 2025-06-04 14:40:16 UTC

name: Build Android APK

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Configure Gradle
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > ~/.gradle/gradle.properties
          echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
          echo "org.gradle.caching=true" >> ~/.gradle/gradle.properties
          echo "android.useAndroidX=true" >> ~/.gradle/gradle.properties
          echo "android.enableJetifier=true" >> ~/.gradle/gradle.properties

      - name: Generate debug keystore
        run: |
          mkdir -p .android
          keytool -genkeypair \
            -keystore .android/debug.keystore \
            -storepass android \
            -keypass android \
            -alias androiddebugkey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US" \
            -v

      - name: Build and Extract Errors
        id: build
        continue-on-error: true
        shell: bash
        run: |
          chmod +x ./gradlew
          ./gradlew clean --refresh-dependencies --stacktrace
          ./gradlew assembleRelease --stacktrace --info > build_output.txt 2>&1 || true

          if [ -f build_output.txt ]; then
            # Extract specific error patterns
            grep -E "e: .*\.kt:[0-9]+:[0-9]+|error:|Unresolved reference:|cannot find symbol|Exception|Caused by|Execution failed for task|resource linking failed|resource .+ not found" \
              build_output.txt > errors_only.txt || true

            if [ ! -s errors_only.txt ]; then
              echo "No specific errors found. Showing last relevant output:" > errors_only.txt
              echo "----------------------------------------" >> errors_only.txt
              tail -n 50 build_output.txt >> errors_only.txt
            fi
          else
            echo "Build process failed to create output log!" > errors_only.txt
          fi

      - name: Upload Error Log
        uses: actions/upload-artifact@v4
        with:
          name: Build-Errors-${{ github.run_number }}
          path: errors_only.txt
          retention-days: 7

      - name: Sign APK if exists
        if: always()
        run: |
          APK_PATH="app/build/outputs/apk/release/app-release-unsigned.apk"
          if [ -f "$APK_PATH" ]; then
            echo "APK_EXISTS=true" >> $GITHUB_ENV

            ZIPALIGN=$(find $ANDROID_HOME/build-tools -name zipalign | sort -r | head -n 1)
            APKSIGNER=$(find $ANDROID_HOME/build-tools -name apksigner | sort -r | head -n 1)

            echo "Using zipalign: $ZIPALIGN"
            echo "Using apksigner: $APKSIGNER"

            $ZIPALIGN -v -p 4 "$APK_PATH" aligned.apk

            $APKSIGNER sign \
              --ks .android/debug.keystore \
              --ks-pass pass:android \
              --key-pass pass:android \
              --out Pdf_Reader-release-signed.apk \
              aligned.apk

            $APKSIGNER verify --verbose Pdf_Reader-release-signed.apk
          else
            echo "APK_EXISTS=false" >> $GITHUB_ENV
            echo "No APK found at $APK_PATH"
          fi

      - name: Upload Signed Release APK
        if: env.APK_EXISTS == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Pdf_Reader-Release-${{ github.run_number }}
          path: Pdf_Reader-release-signed.apk
          retention-days: 30

      - name: Build Debug APK
        if: env.APK_EXISTS != 'true'
        run: |
          ./gradlew assembleDebug --stacktrace || {
            grep -E "e: .*\.kt:[0-9]+:[0-9]+|error:|Unresolved reference:|cannot find symbol|Exception|Caused by|Execution failed for task|resource linking failed|resource .+ not found" \
              debug_build.log > debug_errors.txt || true
            exit 1
          }
          echo "DEBUG_APK_EXISTS=true" >> $GITHUB_ENV

      - name: Upload Debug APK
        if: env.APK_EXISTS != 'true' && env.DEBUG_APK_EXISTS == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Pdf_Reader-Debug-${{ github.run_number }}
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
