# File: .github/workflows/android.yml
# Created: 2025-06-04
# Author: Vishalsnw
# Last Modified: 2025-06-04 05:47:16 UTC

name: Build Android APK

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main, master ]  # Added for automatic builds
  pull_request:
    branches: [ main, master ]  # Added for PR checks

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'  # Added Gradle caching

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Generate debug keystore
        run: |
          mkdir -p .github/keystore
          keytool -genkey -v \
            -keystore .github/keystore/debug.keystore \
            -alias androiddebugkey \
            -storepass android \
            -keypass android \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Force refresh and build Release APK
        id: build
        continue-on-error: true
        shell: bash
        run: |
          # Add Gradle properties for better build performance
          mkdir -p ~/.gradle
          echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" >> ~/.gradle/gradle.properties
          echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
          echo "org.gradle.caching=true" >> ~/.gradle/gradle.properties
          
          set -o pipefail
          ./gradlew clean --refresh-dependencies --stacktrace
          ./gradlew assembleRelease --stacktrace --info > build_output.txt 2>&1 || true

          if [ -f build_output.txt ]; then
            grep -E "e: .*\.kt:[0-9]+:[0-9]+|error:|Unresolved reference:|cannot find symbol|Exception|Caused by|Execution failed for task|resource linking failed|resource .+ not found" \
              build_output.txt > errors_only.txt || true

            if [ ! -s errors_only.txt ]; then
              echo "No error patterns detected in the build log." > errors_only.txt
              echo "Last 50 lines of build output:" >> errors_only.txt
              tail -n 50 build_output.txt >> errors_only.txt
            fi
          else
            echo "Build log not found!" > errors_only.txt
          fi

      - name: Upload error-only log
        uses: actions/upload-artifact@v4
        with:
          name: Build-Errors-${{ github.run_number }}
          path: errors_only.txt
          retention-days: 7

      - name: Sign APK if exists
        if: always()
        run: |
          APK_PATH="app/build/outputs/apk/release/app-release-unsigned.apk"
          if [ -f "$APK_PATH" ]; then
            echo "APK_EXISTS=true" >> $GITHUB_ENV

            ZIPALIGN=$(find $ANDROID_HOME/build-tools -name zipalign | sort -r | head -n 1)
            APKSIGNER=$(find $ANDROID_HOME/build-tools -name apksigner | sort -r | head -n 1)

            echo "Using zipalign: $ZIPALIGN"
            echo "Using apksigner: $APKSIGNER"

            $ZIPALIGN -v -p 4 "$APK_PATH" aligned.apk

            $APKSIGNER sign \
              --ks .github/keystore/debug.keystore \
              --ks-pass pass:android \
              --key-pass pass:android \
              --out Pdf_Reader-release-signed.apk \
              aligned.apk

            $APKSIGNER verify --verbose Pdf_Reader-release-signed.apk
          else
            echo "APK_EXISTS=false" >> $GITHUB_ENV
            echo "No APK found at $APK_PATH"
          fi

      - name: Upload signed APK
        if: env.APK_EXISTS == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Pdf_Reader-Release-${{ github.run_number }}
          path: Pdf_Reader-release-signed.apk
          retention-days: 30

      # Added debug APK build as fallback
      - name: Build Debug APK
        if: env.APK_EXISTS != 'true'
        run: |
          ./gradlew assembleDebug --stacktrace
          echo "DEBUG_APK_EXISTS=true" >> $GITHUB_ENV

      - name: Upload Debug APK
        if: env.APK_EXISTS != 'true' && env.DEBUG_APK_EXISTS == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Pdf_Reader-Debug-${{ github.run_number }}
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
